#!/bin/sh
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
set -eu

n=0
max=2
export UBI8_FRONTEND=noninteractive

until [ $n -gt $max ]; do
    set +e
    (
      dnf update &&
      dnf install -y "$@"
    )
    CODE=$?
    set -e
    if [ $CODE -eq 0 ]; then
        break
    fi
    if [ $n -eq $max ]; then
        exit $CODE
    fi
    echo "dnf failed, retrying"
    n=$(($n + 1))
done
dnf clean all
